# Generated by Django 4.0.3 on 2022-03-31 09:56

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('phone', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('line_id', models.CharField(blank=True, default='', max_length=255, null=True, unique=True)),
                ('vehicalLicence', models.CharField(default='', max_length=255)),
                ('userId', models.CharField(default='', max_length=10)),
                ('idNumber', models.CharField(default='', max_length=20)),
                ('gender', models.CharField(default='', max_length=10)),
                ('type', models.CharField(default='', max_length=20)),
                ('category', models.CharField(default='', max_length=20)),
                ('car_model', models.CharField(default='', max_length=128)),
                ('car_color', models.CharField(default='', max_length=20)),
                ('number_sites', models.IntegerField(default=0)),
                ('is_online', models.BooleanField(default=False)),
                ('left_money', models.IntegerField(default=0)),
                ('is_passed', models.BooleanField(default=False)),
                ('current_lat', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('current_lng', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('dispatch_fee_percent_integer', models.IntegerField(default=10, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)])),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_state', models.CharField(default='', max_length=20)),
                ('customer_name', models.CharField(default='', max_length=128)),
                ('customer_phone', models.CharField(default='', max_length=20)),
                ('on_lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('on_lng', models.DecimalField(decimal_places=6, max_digits=9)),
                ('on_address', models.CharField(default='', max_length=255)),
                ('off_lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('off_lng', models.DecimalField(decimal_places=6, max_digits=9)),
                ('off_address', models.CharField(default='', max_length=255)),
                ('case_money', models.IntegerField(default=0)),
                ('memo', models.TextField(default='')),
                ('create_time', models.DateTimeField(null=True)),
                ('confirm_time', models.DateTimeField(null=True)),
                ('arrived_time', models.DateTimeField(null=True)),
                ('catched_time', models.DateTimeField(null=True)),
                ('off_time', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MonthSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_date', models.DateField(null=True)),
                ('month_increase_money', models.IntegerField(default=0)),
                ('month_decrease_money', models.IntegerField(default=0)),
                ('month_owners', models.CharField(default='', max_length=255)),
                ('month_owners_decrease_money', models.CharField(default='', max_length=255)),
                ('month_driver_arrears', models.IntegerField(default=0)),
                ('total_driver_arrears', models.IntegerField(default=0)),
                ('total_store_money', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='UserStoreMoney',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('increase_money', models.IntegerField(default=0)),
                ('decrease_money', models.IntegerField(default=0)),
                ('sum_money', models.IntegerField(default=0)),
                ('user_left_money', models.IntegerField(default=0)),
                ('date', models.DateTimeField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserCaseShip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(default='state1', max_length=20)),
                ('countdown_second', models.IntegerField(default=20)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='modelCore.case')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=10)),
                ('line_id', models.CharField(blank=True, default='', max_length=255, null=True, unique=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='modelCore.owner')),
            ],
        ),
        migrations.CreateModel(
            name='CaseSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_user_id', models.CharField(default='', max_length=10)),
                ('driver_owner', models.CharField(default='', max_length=128)),
                ('customer_name', models.CharField(default='', max_length=128)),
                ('customer_owner', models.CharField(default='', max_length=128)),
                ('increase_money', models.IntegerField(default=0)),
                ('decrease_money', models.IntegerField(default=0)),
                ('driver_left_money', models.IntegerField(default=0)),
                ('case', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='modelCore.case')),
            ],
        ),
        migrations.AddField(
            model_name='case',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='modelCore.customer'),
        ),
        migrations.AddField(
            model_name='case',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='modelCore.owner'),
        ),
        migrations.AddField(
            model_name='case',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='modelCore.owner'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
