# Generated by Django 4.0.4 on 2022-04-21 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelCore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='userId',
            field=models.CharField(default='', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='owner',
            name='driverNum',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
