# Generated by Django 4.0.4 on 2022-04-21 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelCore', '0002_case_userid_owner_drivernum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='memo',
            field=models.TextField(default='', null=True),
        ),
    ]
