# Generated by Django 4.0.4 on 2022-04-21 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelCore', '0003_alter_case_memo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='line_id',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
