# Generated by Django 4.0.4 on 2022-05-13 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelCore', '0009_alter_user_idnumber_alter_user_userid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='idNumber',
            field=models.CharField(default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='vehicalLicence',
            field=models.CharField(default='', max_length=255, null=True),
        ),
    ]
