# Generated by Django 4.0.4 on 2022-05-24 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelCore', '0010_alter_user_idnumber_alter_user_vehicallicence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userId',
            field=models.CharField(default='', max_length=10, null=True),
        ),
    ]
