# Generated by Django 4.0.4 on 2022-07-07 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelCore', '0011_alter_user_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='case_state',
            field=models.CharField(choices=[('wait', 'wait'), ('way_to_catch', 'way_to_catch'), ('arrived', 'arrived'), ('catched', 'catched'), ('on_road', 'on_road'), ('finished', 'finished'), ('canceled', 'canceled')], default='', max_length=20),
        ),
    ]
