# Generated by Django 4.0.4 on 2022-07-10 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelCore', '0013_alter_case_create_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='create_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
