# Generated by Django 4.0.4 on 2022-07-18 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelCore', '0014_alter_case_create_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userstoremoney',
            name='decrease_money',
        ),
    ]
