# Generated by Django 4.0.4 on 2022-07-25 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelCore', '0015_remove_userstoremoney_decrease_money'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monthsummary',
            name='month_decrease_money',
        ),
        migrations.RemoveField(
            model_name='monthsummary',
            name='month_increase_money',
        ),
        migrations.RemoveField(
            model_name='monthsummary',
            name='month_owners',
        ),
        migrations.RemoveField(
            model_name='monthsummary',
            name='month_owners_decrease_money',
        ),
        migrations.RemoveField(
            model_name='monthsummary',
            name='total_driver_arrears',
        ),
        migrations.RemoveField(
            model_name='monthsummary',
            name='total_store_money',
        ),
        migrations.AddField(
            model_name='monthsummary',
            name='month_owner_a_money',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='monthsummary',
            name='month_owner_b_money',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='monthsummary',
            name='month_store_money',
            field=models.IntegerField(default=0),
        ),
    ]
