# Generated by Django 4.1.5 on 2023-01-17 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelCore', '0017_user_car_memo'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iOS_current_version', models.CharField(blank=True, default='', max_length=10, null=True)),
                ('android_current_version', models.CharField(blank=True, default='', max_length=10, null=True)),
            ],
        ),
    ]
