# Generated by Django 4.1.5 on 2023-01-18 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelCore', '0018_appversion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MonthSummary',
        ),
        migrations.RemoveField(
            model_name='case',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='casesummary',
            name='customer_owner',
        ),
        migrations.RemoveField(
            model_name='casesummary',
            name='driver_owner',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='user',
            name='owner',
        ),
        migrations.DeleteModel(
            name='Owner',
        ),
    ]
