# Generated by Django 4.1.5 on 2023-02-15 01:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modelCore', '0019_delete_monthsummary_remove_case_owner_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('day_case_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='case',
            name='userId',
        ),
        migrations.RemoveField(
            model_name='user',
            name='car_model',
        ),
        migrations.RemoveField(
            model_name='user',
            name='category',
        ),
        migrations.RemoveField(
            model_name='user',
            name='dispatch_fee_percent_integer',
        ),
        migrations.RemoveField(
            model_name='user',
            name='type',
        ),
        migrations.RemoveField(
            model_name='user',
            name='userId',
        ),
        migrations.AddField(
            model_name='case',
            name='case_number',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='nick_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.CreateModel(
            name='UserCarTeamShip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_dispatch', models.BooleanField(default=True)),
                ('carTeam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelCore.carteam')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='case',
            name='carTeam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='modelCore.carteam'),
        ),
    ]
