# Generated by Django 4.1.5 on 2023-02-16 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelCore', '0021_alter_user_idnumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='telegram_id',
            field=models.CharField(blank=True, default='', max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='telegram_id',
            field=models.CharField(blank=True, default='', max_length=128, null=True),
        ),
    ]
