# Generated by Django 4.1.5 on 2023-02-20 05:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modelCore', '0022_case_telegram_id_user_telegram_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercaseship',
            name='countdown_second',
            field=models.IntegerField(default=15),
        ),
        migrations.AlterField(
            model_name='usercaseship',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
    ]
