# Generated by Django 4.1.5 on 2023-02-20 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modelCore', '0023_alter_usercaseship_countdown_second_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='time_memo',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='modelCore.customer'),
        ),
    ]
