# Generated by Django 4.1.5 on 2023-02-21 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelCore', '0024_case_time_memo_alter_case_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercaseship',
            name='state',
        ),
        migrations.AddField(
            model_name='usercaseship',
            name='exclude_ids_text',
            field=models.TextField(default=''),
        ),
    ]
