# Generated by Django 4.1.5 on 2023-02-21 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelCore', '0023_alter_user_nick_name'),
        ('modelCore', '0025_remove_usercaseship_state_and_more'),
    ]

    operations = [
    ]
