# Generated by Django 4.1.5 on 2023-03-04 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelCore', '0028_alter_case_customer_alter_case_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercaseship',
            name='expect_second',
            field=models.IntegerField(default=0),
        ),
    ]
