# Generated by Django 4.1.5 on 2023-03-07 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelCore', '0030_alter_usercaseship_countdown_second'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_telegram_bot_enable',
            field=models.BooleanField(default=True),
        ),
    ]
