# Generated by Django 4.1.5 on 2023-03-16 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelCore', '0032_user_is_on_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercaseship',
            name='ask_ranking_ids_text',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
