# Generated by Django 4.1.5 on 2023-04-06 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelCore', '0033_usercaseship_ask_ranking_ids_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercaseship',
            name='ask_ranking_ids_text',
        ),
        migrations.AddField(
            model_name='usercaseship',
            name='ask_manager_ids_text',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='usercaseship',
            name='ask_no_car_team_ids_text',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='usercaseship',
            name='ask_not_same_car_team_ids_text',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='usercaseship',
            name='ask_same_car_team_ids_text',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
