# Generated by Django 4.2.1 on 2023-05-30 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelCore', '0036_alter_usercaseship_countdown_second'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_in_penalty',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='penalty_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='violation_time',
            field=models.IntegerField(default=0),
        ),
    ]
