# Generated by Django 4.2.1 on 2023-06-17 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelCore', '0037_user_is_in_penalty_user_penalty_datetime_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercaseship',
            name='ask_manager_ids_text',
        ),
        migrations.RemoveField(
            model_name='usercaseship',
            name='ask_no_car_team_ids_text',
        ),
        migrations.RemoveField(
            model_name='usercaseship',
            name='ask_ranking_ids_text',
        ),
    ]
