# Generated by Django 4.2.1 on 2023-06-20 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelCore', '0038_remove_usercaseship_ask_manager_ids_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercaseship',
            name='ask_not_same_car_team_ids_text',
        ),
        migrations.RemoveField(
            model_name='usercaseship',
            name='ask_same_car_team_ids_text',
        ),
        migrations.RemoveField(
            model_name='usercaseship',
            name='countdown_second',
        ),
        migrations.RemoveField(
            model_name='usercaseship',
            name='exclude_ids_text',
        ),
        migrations.AddField(
            model_name='case',
            name='exclude_ids_text',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_asking',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usercaseship',
            name='dispatch_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
