# Generated by Django 4.2.1 on 2023-06-20 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelCore', '0039_remove_usercaseship_ask_not_same_car_team_ids_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='case_state',
            field=models.CharField(choices=[('wait', 'wait'), ('dispatching', 'dispatching'), ('way_to_catch', 'way_to_catch'), ('arrived', 'arrived'), ('catched', 'catched'), ('on_road', 'on_road'), ('finished', 'finished'), ('canceled', 'canceled')], default='', max_length=20),
        ),
    ]
