version: '3.1'
services:
  db:
    image: postgis/postgis:15-3.3-alpine
    restart: always
    environment:
      POSTGRES_USER: mydatabaseuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
       - "5432:5432"
    volumes:
       - ./data:/var/lib/postgresql/data

